name: vrgpsdk
description: Plugin para comunicação com impressora UROVO que utilizar GPSdk
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.vrsoft.vrgpsdk
        pluginClass: VrgpsdkPlugin
      ios:
        pluginClass: VrgpsdkPlugin
      linux:
        pluginClass: VrgpsdkPlugin
      macos:
        pluginClass: VrgpsdkPlugin
      windows:
        pluginClass: VrgpsdkPluginCApi
      web:
        pluginClass: VrgpsdkWeb
        fileName: vrgpsdk_web.dart
